/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OSUPAD_OSUPAD_PB_H_INCLUDED
#define PB_OSUPAD_OSUPAD_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Protocol version definition */
typedef enum _osupad_ProtocolVersion {
    osupad_ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED = 0,
    osupad_ProtocolVersion_PROTOCOL_VERSION_V1 = 1
} osupad_ProtocolVersion;

/* System / Operational state */
typedef enum _osupad_DeviceState {
    osupad_DeviceState_DEVICE_STATE_UNKNOWN = 0,
    osupad_DeviceState_DEVICE_STATE_IDLE = 1,
    osupad_DeviceState_DEVICE_STATE_PLAYING = 2,
    osupad_DeviceState_DEVICE_STATE_COOLDOWN = 3,
    osupad_DeviceState_DEVICE_STATE_SYNC = 4
} osupad_DeviceState;

/* Severity level for diagnostic events */
typedef enum _osupad_LogLevel {
    osupad_LogLevel_LOG_LEVEL_DEBUG = 0,
    osupad_LogLevel_LOG_LEVEL_INFO = 1,
    osupad_LogLevel_LOG_LEVEL_WARN = 2,
    osupad_LogLevel_LOG_LEVEL_ERROR = 3
} osupad_LogLevel;

/* Struct definitions */
typedef struct _osupad_Hello {
    uint32_t protocol_version;
    char client_version[32];
} osupad_Hello;

typedef struct _osupad_HelloAck {
    uint32_t protocol_version;
    char firmware_version[32];
    char board_profile[32];
    char device_id[32];
    uint32_t counter_generation;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
} osupad_HelloAck;

typedef struct _osupad_DeviceStatus {
    uint32_t uptime_seconds;
    osupad_DeviceState state;
    uint32_t brightness;
    bool display_asleep;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
    uint32_t map_key1;
    uint32_t map_key2;
    /* Key edge (GPIO ISR) to HID report submit, since boot or last reset */
    uint32_t latency_samples;
    uint32_t latency_p50_us;
    uint32_t latency_p99_us;
    uint32_t latency_p999_us;
    uint32_t latency_max_us;
    uint32_t hid_dropped_reports; /* Reports not submitted because the endpoint was busy */
} osupad_DeviceStatus;

typedef struct _osupad_ConfigPayload {
    uint32_t key1_hid_usage; /* Default: 0x1D ('Z') */
    uint32_t key2_hid_usage; /* Default: 0x1B ('X') */
    uint32_t debounce_us; /* Lockout window, default: 3000 (3ms) */
    uint32_t brightness; /* 0 to 100%, default: 100 */
    uint32_t display_sleep_seconds; /* Inactivity timeout, default: 600 (10 min) */
    uint32_t gameplay_display_hz; /* Gameplay refresh rate cap, default: 5 */
    uint32_t press_color_rgb; /* Key press highlight 0xRRGGBB on the gameplay screen, 0 = unchanged */
} osupad_ConfigPayload;

typedef struct _osupad_SetConfig {
    bool has_config;
    osupad_ConfigPayload config;
} osupad_SetConfig;

typedef struct _osupad_ConfigAck {
    bool success;
    char message[64];
    bool has_current_config;
    osupad_ConfigPayload current_config;
} osupad_ConfigAck;

typedef struct _osupad_TimeSync {
    uint32_t year;
    uint32_t month; /* 1 - 12 */
    uint32_t day; /* 1 - 31 */
    uint32_t hour; /* 0 - 23 */
    uint32_t minute; /* 0 - 59 */
    uint32_t second; /* 0 - 59 */
} osupad_TimeSync;

typedef struct _osupad_GameplayDisplayState {
    char title[64];
    char artist[64];
    float current_pp;
    float progress_ratio; /* 0.0 to 1.0 */
    uint32_t current_map_presses_k1;
    uint32_t current_map_presses_k2;
    uint32_t play_id; /* Changes on every new attempt (new map, retry); device zeroes map counters */
    char difficulty[32]; /* Difficulty name, e.g. "Lunatic" */
    float stars; /* Star rating including mods */
} osupad_GameplayDisplayState;

/* Host-side integration status, sent periodically and on every change */
typedef struct _osupad_HostStatus {
    bool tosu_connected; /* Daemon has a live tosu WebSocket */
    bool playing; /* osu! is currently playing a map */
    uint32_t play_id; /* Changes on every new attempt (new map, retry); device zeroes map counters */
} osupad_HostStatus;

/* One UI data source value. Source ids: firmware/main/ui/core/ui_ids.h (ui_source_t) */
typedef struct _osupad_DataValue {
    uint32_t source;
    pb_size_t which_value;
    union {
        double number;
        char text[64];
        bool clear; /* Source has no value */
    } value;
} osupad_DataValue;

/* Changed data source values only; the host resends everything after a reconnect */
typedef struct _osupad_DataUpdate {
    pb_size_t values_count;
    osupad_DataValue values[32];
} osupad_DataUpdate;

typedef struct _osupad_UiWidget {
    uint32_t kind; /* ui_widget_kind_t */
    uint32_t source; /* ui_source_t */
    uint32_t font; /* ui_font_id_t */
    uint32_t align; /* ui_align_t */
    int32_t x;
    int32_t y;
    uint32_t w;
    uint32_t h;
    uint32_t fg; /* 0xRRGGBB */
    uint32_t bg;
    uint32_t accent;
    uint32_t radius;
    uint32_t decimals; /* 255 = source default */
    uint32_t flags; /* UI_FLAG_* */
    char label[32];
    char suffix[12];
} osupad_UiWidget;

typedef struct _osupad_SetLayout {
    uint32_t screen; /* ui_screen_id_t */
    uint32_t background; /* 0xRRGGBB */
    pb_size_t widgets_count;
    osupad_UiWidget widgets[32];
} osupad_SetLayout;

typedef struct _osupad_LayoutAck {
    uint32_t screen;
    bool success;
    char message[64];
} osupad_LayoutAck;

typedef struct _osupad_CounterState {
    char device_id[32];
    uint32_t counter_generation;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
} osupad_CounterState;

typedef struct _osupad_CounterSyncRequest {
    bool has_target_state;
    osupad_CounterState target_state;
    bool force_restore; /* Explicit restore from PC/Backup */
} osupad_CounterSyncRequest;

typedef struct _osupad_CounterSyncResponse {
    bool success;
    bool has_synchronized_state;
    osupad_CounterState synchronized_state;
} osupad_CounterSyncResponse;

typedef struct _osupad_LogEvent {
    uint32_t timestamp_ms;
    osupad_LogLevel level;
    char tag[16];
    char message[64];
} osupad_LogEvent;

typedef struct _osupad_LogEventBatch {
    pb_size_t events_count;
    osupad_LogEvent events[8];
} osupad_LogEventBatch;

typedef struct _osupad_HostToDevice {
    uint32_t sequence_number;
    pb_size_t which_payload;
    union {
        osupad_Hello hello;
        osupad_SetConfig set_config;
        osupad_TimeSync time_sync;
        osupad_GameplayDisplayState gameplay_state;
        osupad_CounterSyncRequest counter_sync;
        bool request_status;
        osupad_HostStatus host_status;
        bool reset_latency_stats;
        osupad_DataUpdate data_update;
        osupad_SetLayout set_layout;
        uint32_t reset_layout; /* screen id: back to the built-in default */
    } payload;
} osupad_HostToDevice;

typedef struct _osupad_DeviceToHost {
    uint32_t sequence_number;
    pb_size_t which_payload;
    union {
        osupad_HelloAck hello_ack;
        osupad_DeviceStatus status;
        osupad_ConfigAck config_ack;
        osupad_CounterSyncResponse counter_sync_resp;
        osupad_LogEventBatch log_batch;
        osupad_LayoutAck layout_ack;
    } payload;
} osupad_DeviceToHost;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _osupad_ProtocolVersion_MIN osupad_ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED
#define _osupad_ProtocolVersion_MAX osupad_ProtocolVersion_PROTOCOL_VERSION_V1
#define _osupad_ProtocolVersion_ARRAYSIZE ((osupad_ProtocolVersion)(osupad_ProtocolVersion_PROTOCOL_VERSION_V1+1))

#define _osupad_DeviceState_MIN osupad_DeviceState_DEVICE_STATE_UNKNOWN
#define _osupad_DeviceState_MAX osupad_DeviceState_DEVICE_STATE_SYNC
#define _osupad_DeviceState_ARRAYSIZE ((osupad_DeviceState)(osupad_DeviceState_DEVICE_STATE_SYNC+1))

#define _osupad_LogLevel_MIN osupad_LogLevel_LOG_LEVEL_DEBUG
#define _osupad_LogLevel_MAX osupad_LogLevel_LOG_LEVEL_ERROR
#define _osupad_LogLevel_ARRAYSIZE ((osupad_LogLevel)(osupad_LogLevel_LOG_LEVEL_ERROR+1))



#define osupad_DeviceStatus_state_ENUMTYPE osupad_DeviceState















#define osupad_LogEvent_level_ENUMTYPE osupad_LogLevel





/* Initializer values for message structs */
#define osupad_Hello_init_default                {0, ""}
#define osupad_HelloAck_init_default             {0, "", "", "", 0, 0, 0}
#define osupad_DeviceStatus_init_default         {0, _osupad_DeviceState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define osupad_ConfigPayload_init_default        {0, 0, 0, 0, 0, 0, 0}
#define osupad_SetConfig_init_default            {false, osupad_ConfigPayload_init_default}
#define osupad_ConfigAck_init_default            {0, "", false, osupad_ConfigPayload_init_default}
#define osupad_TimeSync_init_default             {0, 0, 0, 0, 0, 0}
#define osupad_GameplayDisplayState_init_default {"", "", 0, 0, 0, 0, 0, "", 0}
#define osupad_HostStatus_init_default           {0, 0, 0}
#define osupad_DataValue_init_default            {0, 0, {0}}
#define osupad_DataUpdate_init_default           {0, {osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default, osupad_DataValue_init_default}}
#define osupad_UiWidget_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", ""}
#define osupad_SetLayout_init_default            {0, 0, 0, {osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default, osupad_UiWidget_init_default}}
#define osupad_LayoutAck_init_default            {0, 0, ""}
#define osupad_CounterState_init_default         {"", 0, 0, 0}
#define osupad_CounterSyncRequest_init_default   {false, osupad_CounterState_init_default, 0}
#define osupad_CounterSyncResponse_init_default  {0, false, osupad_CounterState_init_default}
#define osupad_LogEvent_init_default             {0, _osupad_LogLevel_MIN, "", ""}
#define osupad_LogEventBatch_init_default        {0, {osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default}}
#define osupad_HostToDevice_init_default         {0, 0, {osupad_Hello_init_default}}
#define osupad_DeviceToHost_init_default         {0, 0, {osupad_HelloAck_init_default}}
#define osupad_Hello_init_zero                   {0, ""}
#define osupad_HelloAck_init_zero                {0, "", "", "", 0, 0, 0}
#define osupad_DeviceStatus_init_zero            {0, _osupad_DeviceState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define osupad_ConfigPayload_init_zero           {0, 0, 0, 0, 0, 0, 0}
#define osupad_SetConfig_init_zero               {false, osupad_ConfigPayload_init_zero}
#define osupad_ConfigAck_init_zero               {0, "", false, osupad_ConfigPayload_init_zero}
#define osupad_TimeSync_init_zero                {0, 0, 0, 0, 0, 0}
#define osupad_GameplayDisplayState_init_zero    {"", "", 0, 0, 0, 0, 0, "", 0}
#define osupad_HostStatus_init_zero              {0, 0, 0}
#define osupad_DataValue_init_zero               {0, 0, {0}}
#define osupad_DataUpdate_init_zero              {0, {osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero, osupad_DataValue_init_zero}}
#define osupad_UiWidget_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", ""}
#define osupad_SetLayout_init_zero               {0, 0, 0, {osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero, osupad_UiWidget_init_zero}}
#define osupad_LayoutAck_init_zero               {0, 0, ""}
#define osupad_CounterState_init_zero            {"", 0, 0, 0}
#define osupad_CounterSyncRequest_init_zero      {false, osupad_CounterState_init_zero, 0}
#define osupad_CounterSyncResponse_init_zero     {0, false, osupad_CounterState_init_zero}
#define osupad_LogEvent_init_zero                {0, _osupad_LogLevel_MIN, "", ""}
#define osupad_LogEventBatch_init_zero           {0, {osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero}}
#define osupad_HostToDevice_init_zero            {0, 0, {osupad_Hello_init_zero}}
#define osupad_DeviceToHost_init_zero            {0, 0, {osupad_HelloAck_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define osupad_Hello_protocol_version_tag        1
#define osupad_Hello_client_version_tag          2
#define osupad_HelloAck_protocol_version_tag     1
#define osupad_HelloAck_firmware_version_tag     2
#define osupad_HelloAck_board_profile_tag        3
#define osupad_HelloAck_device_id_tag            4
#define osupad_HelloAck_counter_generation_tag   5
#define osupad_HelloAck_lifetime_key1_tag        6
#define osupad_HelloAck_lifetime_key2_tag        7
#define osupad_DeviceStatus_uptime_seconds_tag   1
#define osupad_DeviceStatus_state_tag            2
#define osupad_DeviceStatus_brightness_tag       3
#define osupad_DeviceStatus_display_asleep_tag   4
#define osupad_DeviceStatus_lifetime_key1_tag    5
#define osupad_DeviceStatus_lifetime_key2_tag    6
#define osupad_DeviceStatus_map_key1_tag         7
#define osupad_DeviceStatus_map_key2_tag         8
#define osupad_DeviceStatus_latency_samples_tag  9
#define osupad_DeviceStatus_latency_p50_us_tag   10
#define osupad_DeviceStatus_latency_p99_us_tag   11
#define osupad_DeviceStatus_latency_p999_us_tag  12
#define osupad_DeviceStatus_latency_max_us_tag   13
#define osupad_DeviceStatus_hid_dropped_reports_tag 14
#define osupad_ConfigPayload_key1_hid_usage_tag  1
#define osupad_ConfigPayload_key2_hid_usage_tag  2
#define osupad_ConfigPayload_debounce_us_tag     3
#define osupad_ConfigPayload_brightness_tag      4
#define osupad_ConfigPayload_display_sleep_seconds_tag 5
#define osupad_ConfigPayload_gameplay_display_hz_tag 6
#define osupad_ConfigPayload_press_color_rgb_tag 7
#define osupad_SetConfig_config_tag              1
#define osupad_ConfigAck_success_tag             1
#define osupad_ConfigAck_message_tag             2
#define osupad_ConfigAck_current_config_tag      3
#define osupad_TimeSync_year_tag                 1
#define osupad_TimeSync_month_tag                2
#define osupad_TimeSync_day_tag                  3
#define osupad_TimeSync_hour_tag                 4
#define osupad_TimeSync_minute_tag               5
#define osupad_TimeSync_second_tag               6
#define osupad_GameplayDisplayState_title_tag    1
#define osupad_GameplayDisplayState_artist_tag   2
#define osupad_GameplayDisplayState_current_pp_tag 3
#define osupad_GameplayDisplayState_progress_ratio_tag 4
#define osupad_GameplayDisplayState_current_map_presses_k1_tag 5
#define osupad_GameplayDisplayState_current_map_presses_k2_tag 6
#define osupad_GameplayDisplayState_play_id_tag  7
#define osupad_GameplayDisplayState_difficulty_tag 8
#define osupad_GameplayDisplayState_stars_tag    9
#define osupad_HostStatus_tosu_connected_tag     1
#define osupad_HostStatus_playing_tag            2
#define osupad_HostStatus_play_id_tag            3
#define osupad_DataValue_source_tag              1
#define osupad_DataValue_number_tag              2
#define osupad_DataValue_text_tag                3
#define osupad_DataValue_clear_tag               4
#define osupad_DataUpdate_values_tag             1
#define osupad_UiWidget_kind_tag                 1
#define osupad_UiWidget_source_tag               2
#define osupad_UiWidget_font_tag                 3
#define osupad_UiWidget_align_tag                4
#define osupad_UiWidget_x_tag                    5
#define osupad_UiWidget_y_tag                    6
#define osupad_UiWidget_w_tag                    7
#define osupad_UiWidget_h_tag                    8
#define osupad_UiWidget_fg_tag                   9
#define osupad_UiWidget_bg_tag                   10
#define osupad_UiWidget_accent_tag               11
#define osupad_UiWidget_radius_tag               12
#define osupad_UiWidget_decimals_tag             13
#define osupad_UiWidget_flags_tag                14
#define osupad_UiWidget_label_tag                15
#define osupad_UiWidget_suffix_tag               16
#define osupad_SetLayout_screen_tag              1
#define osupad_SetLayout_background_tag          2
#define osupad_SetLayout_widgets_tag             3
#define osupad_LayoutAck_screen_tag              1
#define osupad_LayoutAck_success_tag             2
#define osupad_LayoutAck_message_tag             3
#define osupad_CounterState_device_id_tag        1
#define osupad_CounterState_counter_generation_tag 2
#define osupad_CounterState_lifetime_key1_tag    3
#define osupad_CounterState_lifetime_key2_tag    4
#define osupad_CounterSyncRequest_target_state_tag 1
#define osupad_CounterSyncRequest_force_restore_tag 2
#define osupad_CounterSyncResponse_success_tag   1
#define osupad_CounterSyncResponse_synchronized_state_tag 2
#define osupad_LogEvent_timestamp_ms_tag         1
#define osupad_LogEvent_level_tag                2
#define osupad_LogEvent_tag_tag                  3
#define osupad_LogEvent_message_tag              4
#define osupad_LogEventBatch_events_tag          1
#define osupad_HostToDevice_sequence_number_tag  1
#define osupad_HostToDevice_hello_tag            2
#define osupad_HostToDevice_set_config_tag       3
#define osupad_HostToDevice_time_sync_tag        4
#define osupad_HostToDevice_gameplay_state_tag   5
#define osupad_HostToDevice_counter_sync_tag     6
#define osupad_HostToDevice_request_status_tag   7
#define osupad_HostToDevice_host_status_tag      8
#define osupad_HostToDevice_reset_latency_stats_tag 9
#define osupad_HostToDevice_data_update_tag      10
#define osupad_HostToDevice_set_layout_tag       11
#define osupad_HostToDevice_reset_layout_tag     12
#define osupad_DeviceToHost_sequence_number_tag  1
#define osupad_DeviceToHost_hello_ack_tag        2
#define osupad_DeviceToHost_status_tag           3
#define osupad_DeviceToHost_config_ack_tag       4
#define osupad_DeviceToHost_counter_sync_resp_tag 5
#define osupad_DeviceToHost_log_batch_tag        6
#define osupad_DeviceToHost_layout_ack_tag       7

/* Struct field encoding specification for nanopb */
#define osupad_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   client_version,    2)
#define osupad_Hello_CALLBACK NULL
#define osupad_Hello_DEFAULT NULL

#define osupad_HelloAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   board_profile,     3) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         4) \
X(a, STATIC,   SINGULAR, UINT32,   counter_generation,   5) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     6) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     7)
#define osupad_HelloAck_CALLBACK NULL
#define osupad_HelloAck_DEFAULT NULL

#define osupad_DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        3) \
X(a, STATIC,   SINGULAR, BOOL,     display_asleep,    4) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     5) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     6) \
X(a, STATIC,   SINGULAR, UINT32,   map_key1,          7) \
X(a, STATIC,   SINGULAR, UINT32,   map_key2,          8) \
X(a, STATIC,   SINGULAR, UINT32,   latency_samples,   9) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p50_us,   10) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p99_us,   11) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p999_us,  12) \
X(a, STATIC,   SINGULAR, UINT32,   latency_max_us,   13) \
X(a, STATIC,   SINGULAR, UINT32,   hid_dropped_reports,  14)
#define osupad_DeviceStatus_CALLBACK NULL
#define osupad_DeviceStatus_DEFAULT NULL

#define osupad_ConfigPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key1_hid_usage,    1) \
X(a, STATIC,   SINGULAR, UINT32,   key2_hid_usage,    2) \
X(a, STATIC,   SINGULAR, UINT32,   debounce_us,       3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4) \
X(a, STATIC,   SINGULAR, UINT32,   display_sleep_seconds,   5) \
X(a, STATIC,   SINGULAR, UINT32,   gameplay_display_hz,   6) \
X(a, STATIC,   SINGULAR, UINT32,   press_color_rgb,   7)
#define osupad_ConfigPayload_CALLBACK NULL
#define osupad_ConfigPayload_DEFAULT NULL

#define osupad_SetConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define osupad_SetConfig_CALLBACK NULL
#define osupad_SetConfig_DEFAULT NULL
#define osupad_SetConfig_config_MSGTYPE osupad_ConfigPayload

#define osupad_ConfigAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_config,    3)
#define osupad_ConfigAck_CALLBACK NULL
#define osupad_ConfigAck_DEFAULT NULL
#define osupad_ConfigAck_current_config_MSGTYPE osupad_ConfigPayload

#define osupad_TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   year,              1) \
X(a, STATIC,   SINGULAR, UINT32,   month,             2) \
X(a, STATIC,   SINGULAR, UINT32,   day,               3) \
X(a, STATIC,   SINGULAR, UINT32,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT32,   minute,            5) \
X(a, STATIC,   SINGULAR, UINT32,   second,            6)
#define osupad_TimeSync_CALLBACK NULL
#define osupad_TimeSync_DEFAULT NULL

#define osupad_GameplayDisplayState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   title,             1) \
X(a, STATIC,   SINGULAR, STRING,   artist,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    current_pp,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    progress_ratio,    4) \
X(a, STATIC,   SINGULAR, UINT32,   current_map_presses_k1,   5) \
X(a, STATIC,   SINGULAR, UINT32,   current_map_presses_k2,   6) \
X(a, STATIC,   SINGULAR, UINT32,   play_id,           7) \
X(a, STATIC,   SINGULAR, STRING,   difficulty,        8) \
X(a, STATIC,   SINGULAR, FLOAT,    stars,             9)
#define osupad_GameplayDisplayState_CALLBACK NULL
#define osupad_GameplayDisplayState_DEFAULT NULL

#define osupad_HostStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     tosu_connected,    1) \
X(a, STATIC,   SINGULAR, BOOL,     playing,           2) \
X(a, STATIC,   SINGULAR, UINT32,   play_id,           3)
#define osupad_HostStatus_CALLBACK NULL
#define osupad_HostStatus_DEFAULT NULL

#define osupad_DataValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   source,            1) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,number,value.number),   2) \
X(a, STATIC,   ONEOF,    STRING,   (value,text,value.text),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,clear,value.clear),   4)
#define osupad_DataValue_CALLBACK NULL
#define osupad_DataValue_DEFAULT NULL

#define osupad_DataUpdate_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  values,            1)
#define osupad_DataUpdate_CALLBACK NULL
#define osupad_DataUpdate_DEFAULT NULL
#define osupad_DataUpdate_values_MSGTYPE osupad_DataValue

#define osupad_UiWidget_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   kind,              1) \
X(a, STATIC,   SINGULAR, UINT32,   source,            2) \
X(a, STATIC,   SINGULAR, UINT32,   font,              3) \
X(a, STATIC,   SINGULAR, UINT32,   align,             4) \
X(a, STATIC,   SINGULAR, SINT32,   x,                 5) \
X(a, STATIC,   SINGULAR, SINT32,   y,                 6) \
X(a, STATIC,   SINGULAR, UINT32,   w,                 7) \
X(a, STATIC,   SINGULAR, UINT32,   h,                 8) \
X(a, STATIC,   SINGULAR, UINT32,   fg,                9) \
X(a, STATIC,   SINGULAR, UINT32,   bg,               10) \
X(a, STATIC,   SINGULAR, UINT32,   accent,           11) \
X(a, STATIC,   SINGULAR, UINT32,   radius,           12) \
X(a, STATIC,   SINGULAR, UINT32,   decimals,         13) \
X(a, STATIC,   SINGULAR, UINT32,   flags,            14) \
X(a, STATIC,   SINGULAR, STRING,   label,            15) \
X(a, STATIC,   SINGULAR, STRING,   suffix,           16)
#define osupad_UiWidget_CALLBACK NULL
#define osupad_UiWidget_DEFAULT NULL

#define osupad_SetLayout_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screen,            1) \
X(a, STATIC,   SINGULAR, UINT32,   background,        2) \
X(a, STATIC,   REPEATED, MESSAGE,  widgets,           3)
#define osupad_SetLayout_CALLBACK NULL
#define osupad_SetLayout_DEFAULT NULL
#define osupad_SetLayout_widgets_MSGTYPE osupad_UiWidget

#define osupad_LayoutAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screen,            1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define osupad_LayoutAck_CALLBACK NULL
#define osupad_LayoutAck_DEFAULT NULL

#define osupad_CounterState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   counter_generation,   2) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     3) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     4)
#define osupad_CounterState_CALLBACK NULL
#define osupad_CounterState_DEFAULT NULL

#define osupad_CounterSyncRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  target_state,      1) \
X(a, STATIC,   SINGULAR, BOOL,     force_restore,     2)
#define osupad_CounterSyncRequest_CALLBACK NULL
#define osupad_CounterSyncRequest_DEFAULT NULL
#define osupad_CounterSyncRequest_target_state_MSGTYPE osupad_CounterState

#define osupad_CounterSyncResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  synchronized_state,   2)
#define osupad_CounterSyncResponse_CALLBACK NULL
#define osupad_CounterSyncResponse_DEFAULT NULL
#define osupad_CounterSyncResponse_synchronized_state_MSGTYPE osupad_CounterState

#define osupad_LogEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UENUM,    level,             2) \
X(a, STATIC,   SINGULAR, STRING,   tag,               3) \
X(a, STATIC,   SINGULAR, STRING,   message,           4)
#define osupad_LogEvent_CALLBACK NULL
#define osupad_LogEvent_DEFAULT NULL

#define osupad_LogEventBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  events,            1)
#define osupad_LogEventBatch_CALLBACK NULL
#define osupad_LogEventBatch_DEFAULT NULL
#define osupad_LogEventBatch_events_MSGTYPE osupad_LogEvent

#define osupad_HostToDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello,payload.hello),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_config,payload.set_config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,time_sync,payload.time_sync),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gameplay_state,payload.gameplay_state),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,counter_sync,payload.counter_sync),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,request_status,payload.request_status),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,host_status,payload.host_status),   8) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,reset_latency_stats,payload.reset_latency_stats),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,data_update,payload.data_update),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_layout,payload.set_layout),  11) \
X(a, STATIC,   ONEOF,    UINT32,   (payload,reset_layout,payload.reset_layout),  12)
#define osupad_HostToDevice_CALLBACK NULL
#define osupad_HostToDevice_DEFAULT NULL
#define osupad_HostToDevice_payload_hello_MSGTYPE osupad_Hello
#define osupad_HostToDevice_payload_set_config_MSGTYPE osupad_SetConfig
#define osupad_HostToDevice_payload_time_sync_MSGTYPE osupad_TimeSync
#define osupad_HostToDevice_payload_gameplay_state_MSGTYPE osupad_GameplayDisplayState
#define osupad_HostToDevice_payload_counter_sync_MSGTYPE osupad_CounterSyncRequest
#define osupad_HostToDevice_payload_host_status_MSGTYPE osupad_HostStatus
#define osupad_HostToDevice_payload_data_update_MSGTYPE osupad_DataUpdate
#define osupad_HostToDevice_payload_set_layout_MSGTYPE osupad_SetLayout

#define osupad_DeviceToHost_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello_ack,payload.hello_ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config_ack,payload.config_ack),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,counter_sync_resp,payload.counter_sync_resp),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log_batch,payload.log_batch),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,layout_ack,payload.layout_ack),   7)
#define osupad_DeviceToHost_CALLBACK NULL
#define osupad_DeviceToHost_DEFAULT NULL
#define osupad_DeviceToHost_payload_hello_ack_MSGTYPE osupad_HelloAck
#define osupad_DeviceToHost_payload_status_MSGTYPE osupad_DeviceStatus
#define osupad_DeviceToHost_payload_config_ack_MSGTYPE osupad_ConfigAck
#define osupad_DeviceToHost_payload_counter_sync_resp_MSGTYPE osupad_CounterSyncResponse
#define osupad_DeviceToHost_payload_log_batch_MSGTYPE osupad_LogEventBatch
#define osupad_DeviceToHost_payload_layout_ack_MSGTYPE osupad_LayoutAck

extern const pb_msgdesc_t osupad_Hello_msg;
extern const pb_msgdesc_t osupad_HelloAck_msg;
extern const pb_msgdesc_t osupad_DeviceStatus_msg;
extern const pb_msgdesc_t osupad_ConfigPayload_msg;
extern const pb_msgdesc_t osupad_SetConfig_msg;
extern const pb_msgdesc_t osupad_ConfigAck_msg;
extern const pb_msgdesc_t osupad_TimeSync_msg;
extern const pb_msgdesc_t osupad_GameplayDisplayState_msg;
extern const pb_msgdesc_t osupad_HostStatus_msg;
extern const pb_msgdesc_t osupad_DataValue_msg;
extern const pb_msgdesc_t osupad_DataUpdate_msg;
extern const pb_msgdesc_t osupad_UiWidget_msg;
extern const pb_msgdesc_t osupad_SetLayout_msg;
extern const pb_msgdesc_t osupad_LayoutAck_msg;
extern const pb_msgdesc_t osupad_CounterState_msg;
extern const pb_msgdesc_t osupad_CounterSyncRequest_msg;
extern const pb_msgdesc_t osupad_CounterSyncResponse_msg;
extern const pb_msgdesc_t osupad_LogEvent_msg;
extern const pb_msgdesc_t osupad_LogEventBatch_msg;
extern const pb_msgdesc_t osupad_HostToDevice_msg;
extern const pb_msgdesc_t osupad_DeviceToHost_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define osupad_Hello_fields &osupad_Hello_msg
#define osupad_HelloAck_fields &osupad_HelloAck_msg
#define osupad_DeviceStatus_fields &osupad_DeviceStatus_msg
#define osupad_ConfigPayload_fields &osupad_ConfigPayload_msg
#define osupad_SetConfig_fields &osupad_SetConfig_msg
#define osupad_ConfigAck_fields &osupad_ConfigAck_msg
#define osupad_TimeSync_fields &osupad_TimeSync_msg
#define osupad_GameplayDisplayState_fields &osupad_GameplayDisplayState_msg
#define osupad_HostStatus_fields &osupad_HostStatus_msg
#define osupad_DataValue_fields &osupad_DataValue_msg
#define osupad_DataUpdate_fields &osupad_DataUpdate_msg
#define osupad_UiWidget_fields &osupad_UiWidget_msg
#define osupad_SetLayout_fields &osupad_SetLayout_msg
#define osupad_LayoutAck_fields &osupad_LayoutAck_msg
#define osupad_CounterState_fields &osupad_CounterState_msg
#define osupad_CounterSyncRequest_fields &osupad_CounterSyncRequest_msg
#define osupad_CounterSyncResponse_fields &osupad_CounterSyncResponse_msg
#define osupad_LogEvent_fields &osupad_LogEvent_msg
#define osupad_LogEventBatch_fields &osupad_LogEventBatch_msg
#define osupad_HostToDevice_fields &osupad_HostToDevice_msg
#define osupad_DeviceToHost_fields &osupad_DeviceToHost_msg

/* Maximum encoded size of messages (where known) */
#define OSUPAD_OSUPAD_PB_H_MAX_SIZE              osupad_HostToDevice_size
#define osupad_ConfigAck_size                    111
#define osupad_ConfigPayload_size                42
#define osupad_CounterState_size                 61
#define osupad_CounterSyncRequest_size           65
#define osupad_CounterSyncResponse_size          65
#define osupad_DataUpdate_size                   2336
#define osupad_DataValue_size                    71
#define osupad_DeviceStatus_size                 86
#define osupad_DeviceToHost_size                 745
#define osupad_GameplayDisplayState_size         196
#define osupad_HelloAck_size                     133
#define osupad_Hello_size                        39
#define osupad_HostStatus_size                   10
#define osupad_HostToDevice_size                 4309
#define osupad_LayoutAck_size                    73
#define osupad_LogEventBatch_size                736
#define osupad_LogEvent_size                     90
#define osupad_SetConfig_size                    44
#define osupad_SetLayout_size                    4300
#define osupad_TimeSync_size                     36
#define osupad_UiWidget_size                     131

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
