/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OSUPAD_OSUPAD_PB_H_INCLUDED
#define PB_OSUPAD_OSUPAD_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Protocol version definition */
typedef enum _osupad_ProtocolVersion {
    osupad_ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED = 0,
    osupad_ProtocolVersion_PROTOCOL_VERSION_V1 = 1
} osupad_ProtocolVersion;

/* System / Operational state */
typedef enum _osupad_DeviceState {
    osupad_DeviceState_DEVICE_STATE_UNKNOWN = 0,
    osupad_DeviceState_DEVICE_STATE_IDLE = 1,
    osupad_DeviceState_DEVICE_STATE_PLAYING = 2,
    osupad_DeviceState_DEVICE_STATE_COOLDOWN = 3,
    osupad_DeviceState_DEVICE_STATE_SYNC = 4
} osupad_DeviceState;

/* Severity level for diagnostic events */
typedef enum _osupad_LogLevel {
    osupad_LogLevel_LOG_LEVEL_DEBUG = 0,
    osupad_LogLevel_LOG_LEVEL_INFO = 1,
    osupad_LogLevel_LOG_LEVEL_WARN = 2,
    osupad_LogLevel_LOG_LEVEL_ERROR = 3
} osupad_LogLevel;

/* Struct definitions */
typedef struct _osupad_Hello {
    uint32_t protocol_version;
    char client_version[32];
} osupad_Hello;

typedef struct _osupad_HelloAck {
    uint32_t protocol_version;
    char firmware_version[32];
    char board_profile[32];
    char device_id[32];
    uint32_t counter_generation;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
} osupad_HelloAck;

typedef struct _osupad_DeviceStatus {
    uint32_t uptime_seconds;
    osupad_DeviceState state;
    uint32_t brightness;
    bool display_asleep;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
    uint32_t map_key1;
    uint32_t map_key2;
} osupad_DeviceStatus;

typedef struct _osupad_ConfigPayload {
    uint32_t key1_hid_usage; /* Default: 0x1D ('Z') */
    uint32_t key2_hid_usage; /* Default: 0x1B ('X') */
    uint32_t debounce_us; /* Lockout window, default: 3000 (3ms) */
    uint32_t brightness; /* 0 to 100%, default: 100 */
    uint32_t display_sleep_seconds; /* Inactivity timeout, default: 600 (10 min) */
    uint32_t gameplay_display_hz; /* Gameplay refresh rate cap, default: 5 */
} osupad_ConfigPayload;

typedef struct _osupad_SetConfig {
    bool has_config;
    osupad_ConfigPayload config;
} osupad_SetConfig;

typedef struct _osupad_ConfigAck {
    bool success;
    char message[64];
    bool has_current_config;
    osupad_ConfigPayload current_config;
} osupad_ConfigAck;

typedef struct _osupad_TimeSync {
    uint32_t year;
    uint32_t month; /* 1 - 12 */
    uint32_t day; /* 1 - 31 */
    uint32_t hour; /* 0 - 23 */
    uint32_t minute; /* 0 - 59 */
    uint32_t second; /* 0 - 59 */
} osupad_TimeSync;

typedef struct _osupad_GameplayDisplayState {
    char title[64];
    char artist[64];
    float current_pp;
    float progress_ratio; /* 0.0 to 1.0 */
    uint32_t current_map_presses_k1;
    uint32_t current_map_presses_k2;
} osupad_GameplayDisplayState;

typedef struct _osupad_CounterState {
    char device_id[32];
    uint32_t counter_generation;
    uint64_t lifetime_key1;
    uint64_t lifetime_key2;
} osupad_CounterState;

typedef struct _osupad_CounterSyncRequest {
    bool has_target_state;
    osupad_CounterState target_state;
    bool force_restore; /* Explicit restore from PC/Backup */
} osupad_CounterSyncRequest;

typedef struct _osupad_CounterSyncResponse {
    bool success;
    bool has_synchronized_state;
    osupad_CounterState synchronized_state;
} osupad_CounterSyncResponse;

typedef struct _osupad_LogEvent {
    uint32_t timestamp_ms;
    osupad_LogLevel level;
    char tag[16];
    char message[64];
} osupad_LogEvent;

typedef struct _osupad_LogEventBatch {
    pb_size_t events_count;
    osupad_LogEvent events[8];
} osupad_LogEventBatch;

typedef struct _osupad_HostToDevice {
    uint32_t sequence_number;
    pb_size_t which_payload;
    union {
        osupad_Hello hello;
        osupad_SetConfig set_config;
        osupad_TimeSync time_sync;
        osupad_GameplayDisplayState gameplay_state;
        osupad_CounterSyncRequest counter_sync;
        bool request_status;
    } payload;
} osupad_HostToDevice;

typedef struct _osupad_DeviceToHost {
    uint32_t sequence_number;
    pb_size_t which_payload;
    union {
        osupad_HelloAck hello_ack;
        osupad_DeviceStatus status;
        osupad_ConfigAck config_ack;
        osupad_CounterSyncResponse counter_sync_resp;
        osupad_LogEventBatch log_batch;
    } payload;
} osupad_DeviceToHost;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _osupad_ProtocolVersion_MIN osupad_ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED
#define _osupad_ProtocolVersion_MAX osupad_ProtocolVersion_PROTOCOL_VERSION_V1
#define _osupad_ProtocolVersion_ARRAYSIZE ((osupad_ProtocolVersion)(osupad_ProtocolVersion_PROTOCOL_VERSION_V1+1))

#define _osupad_DeviceState_MIN osupad_DeviceState_DEVICE_STATE_UNKNOWN
#define _osupad_DeviceState_MAX osupad_DeviceState_DEVICE_STATE_SYNC
#define _osupad_DeviceState_ARRAYSIZE ((osupad_DeviceState)(osupad_DeviceState_DEVICE_STATE_SYNC+1))

#define _osupad_LogLevel_MIN osupad_LogLevel_LOG_LEVEL_DEBUG
#define _osupad_LogLevel_MAX osupad_LogLevel_LOG_LEVEL_ERROR
#define _osupad_LogLevel_ARRAYSIZE ((osupad_LogLevel)(osupad_LogLevel_LOG_LEVEL_ERROR+1))



#define osupad_DeviceStatus_state_ENUMTYPE osupad_DeviceState









#define osupad_LogEvent_level_ENUMTYPE osupad_LogLevel





/* Initializer values for message structs */
#define osupad_Hello_init_default                {0, ""}
#define osupad_HelloAck_init_default             {0, "", "", "", 0, 0, 0}
#define osupad_DeviceStatus_init_default         {0, _osupad_DeviceState_MIN, 0, 0, 0, 0, 0, 0}
#define osupad_ConfigPayload_init_default        {0, 0, 0, 0, 0, 0}
#define osupad_SetConfig_init_default            {false, osupad_ConfigPayload_init_default}
#define osupad_ConfigAck_init_default            {0, "", false, osupad_ConfigPayload_init_default}
#define osupad_TimeSync_init_default             {0, 0, 0, 0, 0, 0}
#define osupad_GameplayDisplayState_init_default {"", "", 0, 0, 0, 0}
#define osupad_CounterState_init_default         {"", 0, 0, 0}
#define osupad_CounterSyncRequest_init_default   {false, osupad_CounterState_init_default, 0}
#define osupad_CounterSyncResponse_init_default  {0, false, osupad_CounterState_init_default}
#define osupad_LogEvent_init_default             {0, _osupad_LogLevel_MIN, "", ""}
#define osupad_LogEventBatch_init_default        {0, {osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default, osupad_LogEvent_init_default}}
#define osupad_HostToDevice_init_default         {0, 0, {osupad_Hello_init_default}}
#define osupad_DeviceToHost_init_default         {0, 0, {osupad_HelloAck_init_default}}
#define osupad_Hello_init_zero                   {0, ""}
#define osupad_HelloAck_init_zero                {0, "", "", "", 0, 0, 0}
#define osupad_DeviceStatus_init_zero            {0, _osupad_DeviceState_MIN, 0, 0, 0, 0, 0, 0}
#define osupad_ConfigPayload_init_zero           {0, 0, 0, 0, 0, 0}
#define osupad_SetConfig_init_zero               {false, osupad_ConfigPayload_init_zero}
#define osupad_ConfigAck_init_zero               {0, "", false, osupad_ConfigPayload_init_zero}
#define osupad_TimeSync_init_zero                {0, 0, 0, 0, 0, 0}
#define osupad_GameplayDisplayState_init_zero    {"", "", 0, 0, 0, 0}
#define osupad_CounterState_init_zero            {"", 0, 0, 0}
#define osupad_CounterSyncRequest_init_zero      {false, osupad_CounterState_init_zero, 0}
#define osupad_CounterSyncResponse_init_zero     {0, false, osupad_CounterState_init_zero}
#define osupad_LogEvent_init_zero                {0, _osupad_LogLevel_MIN, "", ""}
#define osupad_LogEventBatch_init_zero           {0, {osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero, osupad_LogEvent_init_zero}}
#define osupad_HostToDevice_init_zero            {0, 0, {osupad_Hello_init_zero}}
#define osupad_DeviceToHost_init_zero            {0, 0, {osupad_HelloAck_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define osupad_Hello_protocol_version_tag        1
#define osupad_Hello_client_version_tag          2
#define osupad_HelloAck_protocol_version_tag     1
#define osupad_HelloAck_firmware_version_tag     2
#define osupad_HelloAck_board_profile_tag        3
#define osupad_HelloAck_device_id_tag            4
#define osupad_HelloAck_counter_generation_tag   5
#define osupad_HelloAck_lifetime_key1_tag        6
#define osupad_HelloAck_lifetime_key2_tag        7
#define osupad_DeviceStatus_uptime_seconds_tag   1
#define osupad_DeviceStatus_state_tag            2
#define osupad_DeviceStatus_brightness_tag       3
#define osupad_DeviceStatus_display_asleep_tag   4
#define osupad_DeviceStatus_lifetime_key1_tag    5
#define osupad_DeviceStatus_lifetime_key2_tag    6
#define osupad_DeviceStatus_map_key1_tag         7
#define osupad_DeviceStatus_map_key2_tag         8
#define osupad_ConfigPayload_key1_hid_usage_tag  1
#define osupad_ConfigPayload_key2_hid_usage_tag  2
#define osupad_ConfigPayload_debounce_us_tag     3
#define osupad_ConfigPayload_brightness_tag      4
#define osupad_ConfigPayload_display_sleep_seconds_tag 5
#define osupad_ConfigPayload_gameplay_display_hz_tag 6
#define osupad_SetConfig_config_tag              1
#define osupad_ConfigAck_success_tag             1
#define osupad_ConfigAck_message_tag             2
#define osupad_ConfigAck_current_config_tag      3
#define osupad_TimeSync_year_tag                 1
#define osupad_TimeSync_month_tag                2
#define osupad_TimeSync_day_tag                  3
#define osupad_TimeSync_hour_tag                 4
#define osupad_TimeSync_minute_tag               5
#define osupad_TimeSync_second_tag               6
#define osupad_GameplayDisplayState_title_tag    1
#define osupad_GameplayDisplayState_artist_tag   2
#define osupad_GameplayDisplayState_current_pp_tag 3
#define osupad_GameplayDisplayState_progress_ratio_tag 4
#define osupad_GameplayDisplayState_current_map_presses_k1_tag 5
#define osupad_GameplayDisplayState_current_map_presses_k2_tag 6
#define osupad_CounterState_device_id_tag        1
#define osupad_CounterState_counter_generation_tag 2
#define osupad_CounterState_lifetime_key1_tag    3
#define osupad_CounterState_lifetime_key2_tag    4
#define osupad_CounterSyncRequest_target_state_tag 1
#define osupad_CounterSyncRequest_force_restore_tag 2
#define osupad_CounterSyncResponse_success_tag   1
#define osupad_CounterSyncResponse_synchronized_state_tag 2
#define osupad_LogEvent_timestamp_ms_tag         1
#define osupad_LogEvent_level_tag                2
#define osupad_LogEvent_tag_tag                  3
#define osupad_LogEvent_message_tag              4
#define osupad_LogEventBatch_events_tag          1
#define osupad_HostToDevice_sequence_number_tag  1
#define osupad_HostToDevice_hello_tag            2
#define osupad_HostToDevice_set_config_tag       3
#define osupad_HostToDevice_time_sync_tag        4
#define osupad_HostToDevice_gameplay_state_tag   5
#define osupad_HostToDevice_counter_sync_tag     6
#define osupad_HostToDevice_request_status_tag   7
#define osupad_DeviceToHost_sequence_number_tag  1
#define osupad_DeviceToHost_hello_ack_tag        2
#define osupad_DeviceToHost_status_tag           3
#define osupad_DeviceToHost_config_ack_tag       4
#define osupad_DeviceToHost_counter_sync_resp_tag 5
#define osupad_DeviceToHost_log_batch_tag        6

/* Struct field encoding specification for nanopb */
#define osupad_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   client_version,    2)
#define osupad_Hello_CALLBACK NULL
#define osupad_Hello_DEFAULT NULL

#define osupad_HelloAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   board_profile,     3) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         4) \
X(a, STATIC,   SINGULAR, UINT32,   counter_generation,   5) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     6) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     7)
#define osupad_HelloAck_CALLBACK NULL
#define osupad_HelloAck_DEFAULT NULL

#define osupad_DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        3) \
X(a, STATIC,   SINGULAR, BOOL,     display_asleep,    4) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     5) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     6) \
X(a, STATIC,   SINGULAR, UINT32,   map_key1,          7) \
X(a, STATIC,   SINGULAR, UINT32,   map_key2,          8)
#define osupad_DeviceStatus_CALLBACK NULL
#define osupad_DeviceStatus_DEFAULT NULL

#define osupad_ConfigPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key1_hid_usage,    1) \
X(a, STATIC,   SINGULAR, UINT32,   key2_hid_usage,    2) \
X(a, STATIC,   SINGULAR, UINT32,   debounce_us,       3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4) \
X(a, STATIC,   SINGULAR, UINT32,   display_sleep_seconds,   5) \
X(a, STATIC,   SINGULAR, UINT32,   gameplay_display_hz,   6)
#define osupad_ConfigPayload_CALLBACK NULL
#define osupad_ConfigPayload_DEFAULT NULL

#define osupad_SetConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define osupad_SetConfig_CALLBACK NULL
#define osupad_SetConfig_DEFAULT NULL
#define osupad_SetConfig_config_MSGTYPE osupad_ConfigPayload

#define osupad_ConfigAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_config,    3)
#define osupad_ConfigAck_CALLBACK NULL
#define osupad_ConfigAck_DEFAULT NULL
#define osupad_ConfigAck_current_config_MSGTYPE osupad_ConfigPayload

#define osupad_TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   year,              1) \
X(a, STATIC,   SINGULAR, UINT32,   month,             2) \
X(a, STATIC,   SINGULAR, UINT32,   day,               3) \
X(a, STATIC,   SINGULAR, UINT32,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT32,   minute,            5) \
X(a, STATIC,   SINGULAR, UINT32,   second,            6)
#define osupad_TimeSync_CALLBACK NULL
#define osupad_TimeSync_DEFAULT NULL

#define osupad_GameplayDisplayState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   title,             1) \
X(a, STATIC,   SINGULAR, STRING,   artist,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    current_pp,        3) \
X(a, STATIC,   SINGULAR, FLOAT,    progress_ratio,    4) \
X(a, STATIC,   SINGULAR, UINT32,   current_map_presses_k1,   5) \
X(a, STATIC,   SINGULAR, UINT32,   current_map_presses_k2,   6)
#define osupad_GameplayDisplayState_CALLBACK NULL
#define osupad_GameplayDisplayState_DEFAULT NULL

#define osupad_CounterState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   counter_generation,   2) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key1,     3) \
X(a, STATIC,   SINGULAR, UINT64,   lifetime_key2,     4)
#define osupad_CounterState_CALLBACK NULL
#define osupad_CounterState_DEFAULT NULL

#define osupad_CounterSyncRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  target_state,      1) \
X(a, STATIC,   SINGULAR, BOOL,     force_restore,     2)
#define osupad_CounterSyncRequest_CALLBACK NULL
#define osupad_CounterSyncRequest_DEFAULT NULL
#define osupad_CounterSyncRequest_target_state_MSGTYPE osupad_CounterState

#define osupad_CounterSyncResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  synchronized_state,   2)
#define osupad_CounterSyncResponse_CALLBACK NULL
#define osupad_CounterSyncResponse_DEFAULT NULL
#define osupad_CounterSyncResponse_synchronized_state_MSGTYPE osupad_CounterState

#define osupad_LogEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UENUM,    level,             2) \
X(a, STATIC,   SINGULAR, STRING,   tag,               3) \
X(a, STATIC,   SINGULAR, STRING,   message,           4)
#define osupad_LogEvent_CALLBACK NULL
#define osupad_LogEvent_DEFAULT NULL

#define osupad_LogEventBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  events,            1)
#define osupad_LogEventBatch_CALLBACK NULL
#define osupad_LogEventBatch_DEFAULT NULL
#define osupad_LogEventBatch_events_MSGTYPE osupad_LogEvent

#define osupad_HostToDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello,payload.hello),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_config,payload.set_config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,time_sync,payload.time_sync),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gameplay_state,payload.gameplay_state),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,counter_sync,payload.counter_sync),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,request_status,payload.request_status),   7)
#define osupad_HostToDevice_CALLBACK NULL
#define osupad_HostToDevice_DEFAULT NULL
#define osupad_HostToDevice_payload_hello_MSGTYPE osupad_Hello
#define osupad_HostToDevice_payload_set_config_MSGTYPE osupad_SetConfig
#define osupad_HostToDevice_payload_time_sync_MSGTYPE osupad_TimeSync
#define osupad_HostToDevice_payload_gameplay_state_MSGTYPE osupad_GameplayDisplayState
#define osupad_HostToDevice_payload_counter_sync_MSGTYPE osupad_CounterSyncRequest

#define osupad_DeviceToHost_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello_ack,payload.hello_ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config_ack,payload.config_ack),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,counter_sync_resp,payload.counter_sync_resp),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log_batch,payload.log_batch),   6)
#define osupad_DeviceToHost_CALLBACK NULL
#define osupad_DeviceToHost_DEFAULT NULL
#define osupad_DeviceToHost_payload_hello_ack_MSGTYPE osupad_HelloAck
#define osupad_DeviceToHost_payload_status_MSGTYPE osupad_DeviceStatus
#define osupad_DeviceToHost_payload_config_ack_MSGTYPE osupad_ConfigAck
#define osupad_DeviceToHost_payload_counter_sync_resp_MSGTYPE osupad_CounterSyncResponse
#define osupad_DeviceToHost_payload_log_batch_MSGTYPE osupad_LogEventBatch

extern const pb_msgdesc_t osupad_Hello_msg;
extern const pb_msgdesc_t osupad_HelloAck_msg;
extern const pb_msgdesc_t osupad_DeviceStatus_msg;
extern const pb_msgdesc_t osupad_ConfigPayload_msg;
extern const pb_msgdesc_t osupad_SetConfig_msg;
extern const pb_msgdesc_t osupad_ConfigAck_msg;
extern const pb_msgdesc_t osupad_TimeSync_msg;
extern const pb_msgdesc_t osupad_GameplayDisplayState_msg;
extern const pb_msgdesc_t osupad_CounterState_msg;
extern const pb_msgdesc_t osupad_CounterSyncRequest_msg;
extern const pb_msgdesc_t osupad_CounterSyncResponse_msg;
extern const pb_msgdesc_t osupad_LogEvent_msg;
extern const pb_msgdesc_t osupad_LogEventBatch_msg;
extern const pb_msgdesc_t osupad_HostToDevice_msg;
extern const pb_msgdesc_t osupad_DeviceToHost_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define osupad_Hello_fields &osupad_Hello_msg
#define osupad_HelloAck_fields &osupad_HelloAck_msg
#define osupad_DeviceStatus_fields &osupad_DeviceStatus_msg
#define osupad_ConfigPayload_fields &osupad_ConfigPayload_msg
#define osupad_SetConfig_fields &osupad_SetConfig_msg
#define osupad_ConfigAck_fields &osupad_ConfigAck_msg
#define osupad_TimeSync_fields &osupad_TimeSync_msg
#define osupad_GameplayDisplayState_fields &osupad_GameplayDisplayState_msg
#define osupad_CounterState_fields &osupad_CounterState_msg
#define osupad_CounterSyncRequest_fields &osupad_CounterSyncRequest_msg
#define osupad_CounterSyncResponse_fields &osupad_CounterSyncResponse_msg
#define osupad_LogEvent_fields &osupad_LogEvent_msg
#define osupad_LogEventBatch_fields &osupad_LogEventBatch_msg
#define osupad_HostToDevice_fields &osupad_HostToDevice_msg
#define osupad_DeviceToHost_fields &osupad_DeviceToHost_msg

/* Maximum encoded size of messages (where known) */
#define OSUPAD_OSUPAD_PB_H_MAX_SIZE              osupad_DeviceToHost_size
#define osupad_ConfigAck_size                    105
#define osupad_ConfigPayload_size                36
#define osupad_CounterState_size                 61
#define osupad_CounterSyncRequest_size           65
#define osupad_CounterSyncResponse_size          65
#define osupad_DeviceStatus_size                 50
#define osupad_DeviceToHost_size                 745
#define osupad_GameplayDisplayState_size         152
#define osupad_HelloAck_size                     133
#define osupad_Hello_size                        39
#define osupad_HostToDevice_size                 161
#define osupad_LogEventBatch_size                736
#define osupad_LogEvent_size                     90
#define osupad_SetConfig_size                    38
#define osupad_TimeSync_size                     36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
