/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "osupad.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(osupad_Hello, osupad_Hello, AUTO)


PB_BIND(osupad_HelloAck, osupad_HelloAck, AUTO)


PB_BIND(osupad_ClaimOwnership, osupad_ClaimOwnership, AUTO)


PB_BIND(osupad_DeviceStatus, osupad_DeviceStatus, AUTO)


PB_BIND(osupad_ConfigPayload, osupad_ConfigPayload, AUTO)


PB_BIND(osupad_SetConfig, osupad_SetConfig, AUTO)


PB_BIND(osupad_ConfigAck, osupad_ConfigAck, AUTO)


PB_BIND(osupad_TimeSync, osupad_TimeSync, AUTO)


PB_BIND(osupad_GameplayDisplayState, osupad_GameplayDisplayState, AUTO)


PB_BIND(osupad_HostStatus, osupad_HostStatus, AUTO)


PB_BIND(osupad_DataValue, osupad_DataValue, AUTO)


PB_BIND(osupad_DataUpdate, osupad_DataUpdate, 2)


PB_BIND(osupad_UiWidget, osupad_UiWidget, AUTO)


PB_BIND(osupad_SetLayout, osupad_SetLayout, 2)


PB_BIND(osupad_LayoutAck, osupad_LayoutAck, AUTO)


PB_BIND(osupad_CounterState, osupad_CounterState, AUTO)


PB_BIND(osupad_CounterSyncRequest, osupad_CounterSyncRequest, AUTO)


PB_BIND(osupad_CounterSyncResponse, osupad_CounterSyncResponse, AUTO)


PB_BIND(osupad_LogEvent, osupad_LogEvent, AUTO)


PB_BIND(osupad_LogEventBatch, osupad_LogEventBatch, 2)


PB_BIND(osupad_HostToDevice, osupad_HostToDevice, 2)


PB_BIND(osupad_DeviceToHost, osupad_DeviceToHost, 2)









#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

