[package]
name = "osupad-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
osupad-model = { path = "../osupad-model" }
osupad-layout = { path = "../osupad-layout" }
bytes.workspace = true
byteorder.workspace = true
rustix = { version = "0.38", features = ["process", "fs"] }
