#!/bin/sh
set -e

HERE="$(dirname "$(readlink -f "$0")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"

cmd="$(basename "$0")"
if [ "$cmd" = "osupad-daemon" ] || [ "$cmd" = "osupadctl" ]; then
    exec "${HERE}/usr/bin/${cmd}" "$@"
fi

if [ "$1" = "daemon" ] || [ "$1" = "osupad-daemon" ]; then
    shift
    exec "${HERE}/usr/bin/osupad-daemon" "$@"
elif [ "$1" = "ctl" ] || [ "$1" = "osupadctl" ]; then
    shift
    exec "${HERE}/usr/bin/osupadctl" "$@"
fi

exec "${HERE}/usr/bin/osupad-gui" "$@"
