[package]
publish = false
name = "opadctl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "opadctl"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
opad-model = { path = "../crates/opad-model" }
opad-ipc = { path = "../crates/opad-ipc" }
opad-device = { path = "../crates/opad-device" }
opad-tosu = { path = "../crates/opad-tosu" }
serialport.workspace = true
