[package]
name = "osupad-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "osupad-daemon"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
osupad-model = { path = "../crates/osupad-model" }
osupad-protocol = { path = "../crates/osupad-protocol" }
osupad-storage = { path = "../crates/osupad-storage" }
osupad-ipc = { path = "../crates/osupad-ipc" }
osupad-tosu = { path = "../crates/osupad-tosu" }
osupad-update = { path = "../crates/osupad-update" }
uuid = { version = "1", features = ["v4"] }
osupad-device = { path = "../crates/osupad-device" }
osupad-layout = { path = "../crates/osupad-layout" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
