[package]
name = "opad-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "opad-daemon"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
opad-model = { path = "../crates/opad-model" }
opad-protocol = { path = "../crates/opad-protocol" }
opad-storage = { path = "../crates/opad-storage" }
opad-ipc = { path = "../crates/opad-ipc" }
opad-tosu = { path = "../crates/opad-tosu" }
opad-update = { path = "../crates/opad-update" }
uuid = { version = "1", features = ["v4"] }
opad-device = { path = "../crates/opad-device" }
opad-layout = { path = "../crates/opad-layout" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
