[package]
name = "opad-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
opad-model = { path = "../opad-model" }
opad-layout = { path = "../opad-layout" }
bytes.workspace = true
byteorder.workspace = true

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.38", features = ["process", "fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Threading",
] }
