[package]
name = "osupad-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "osupad-gui"
path = "src/main.rs"

[dependencies]
iced = { workspace = true, features = ["image", "canvas"] }
iced_aw = { version = "0.14.1", default-features = false, features = ["color_picker", "number_input"] }
rfd = "0.15"
osupad-layout = { path = "../crates/osupad-layout" }
osupad-ui-preview = { path = "../crates/osupad-ui-preview" }
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
osupad-model = { path = "../crates/osupad-model" }
osupad-ipc = { path = "../crates/osupad-ipc" }
ksni = "0.3"
futures-util = { workspace = true, features = ["sink"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
