[package]
name = "osupad-device"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serialport.workspace = true
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
chrono.workspace = true
osupad-model = { path = "../osupad-model" }
osupad-layout = { path = "../osupad-layout" }
osupad-protocol = { path = "../osupad-protocol" }
