#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules || true
            udevadm trigger --subsystem-match=tty --subsystem-match=usb || true
        fi
        rm -rf /usr/lib/opad /etc/opad
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        ;;
esac

exit 0
