#!/usr/bin/env python3
"""Generate the "67" easter-egg animation for the firmware.

Writes firmware/main/ui/easter_egg_gif.h: a 180x93, 14-frame GIF embedded as a
byte array, decoded on the pad by LVGL's GIF decoder (see ui/easter_egg.c).

The artwork is drawn here from plain strokes (no font, no source image), so the
whole animation is original OPad work under the repository's MIT license.
Edit the geometry or colours below and re-run:

    python3 scripts/gen_easter_egg_gif.py

Needs Pillow (pip install pillow).
"""

import io
import math
from pathlib import Path

from PIL import Image, ImageDraw

W, H = 180, 93          # easter_egg.c scales and pivots around this size
FRAMES = 14
FRAME_MS = 90
BOB = 4                 # vertical swing of each digit, px
TILT = 9                # rotation swing of each digit, degrees
STROKE = 11             # white stroke width
OUTLINE = 4             # black outline around the stroke
SHADOW = (3, 4)         # pink shadow offset

# Palette indices; 0 is transparent
TRANSPARENT, BLACK, WHITE, PINK = 0, 1, 2, 3
PALETTE = [0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 102, 170]

OUT = Path(__file__).resolve().parent.parent / "firmware/main/ui/easter_egg_gif.h"

# Each digit is drawn on its own 80x90 layer: a list of ("line", points) and
# ("arc", bbox, start, end) strokes, PIL angles (0 = 3 o'clock, clockwise).
SIX = [
    ("ellipse", (21, 43, 57, 73)),
    ("arc", (21, 16, 73, 100), 180, 290),
]
SEVEN = [
    ("line", [(19, 19), (61, 19)]),
    ("line", [(61, 19), (35, 73)]),
]


def stroke_ends(shape):
    """End points of an open stroke, for round caps."""
    if shape[0] == "line":
        return shape[1]
    if shape[0] == "arc":
        (x0, y0, x1, y1), start, end = shape[1], shape[2], shape[3]
        cx, cy, rx, ry = (x0 + x1) / 2, (y0 + y1) / 2, (x1 - x0) / 2, (y1 - y0) / 2
        return [(cx + rx * math.cos(math.radians(a)), cy + ry * math.sin(math.radians(a)))
                for a in (start, end)]
    return []


def draw_strokes(draw, shapes, width, color, dx=0, dy=0):
    for shape in shapes:
        kind = shape[0]
        if kind == "line":
            pts = [(x + dx, y + dy) for x, y in shape[1]]
            draw.line(pts, fill=color, width=width, joint="curve")
        elif kind == "arc":
            x0, y0, x1, y1 = shape[1]
            draw.arc((x0 + dx, y0 + dy, x1 + dx, y1 + dy), shape[2], shape[3],
                     fill=color, width=width)
        elif kind == "ellipse":
            x0, y0, x1, y1 = shape[1]
            half = width / 2
            # Stroke centred on the path, like the lines and arcs
            draw.ellipse((x0 + dx - half, y0 + dy - half, x1 + dx + half, y1 + dy + half),
                         outline=color, width=width)
        for x, y in stroke_ends(shape):
            r = width / 2
            draw.ellipse((x + dx - r, y + dy - r, x + dx + r, y + dy + r), fill=color)


def digit_layer(shapes):
    layer = Image.new("P", (80, 90), TRANSPARENT)
    layer.putpalette(PALETTE)
    d = ImageDraw.Draw(layer)
    draw_strokes(d, shapes, STROKE + 2 * OUTLINE, PINK, *SHADOW)
    draw_strokes(d, shapes, STROKE + 2 * OUTLINE, BLACK)
    draw_strokes(d, shapes, STROKE, WHITE)
    return layer


def frame(i, six, seven):
    # Half-step offset: no two consecutive frames are identical (GIF would merge them)
    t = 2 * math.pi * (i + 0.5) / FRAMES
    img = Image.new("P", (W, H), TRANSPARENT)
    img.putpalette(PALETTE)
    # The two digits rock in opposite directions, like the 6-7 hand gesture
    for layer, cx, phase in ((six, 58, 0.0), (seven, 122, math.pi)):
        swing = math.sin(t + phase)
        rotated = layer.rotate(TILT * swing, resample=Image.NEAREST, expand=True,
                               fillcolor=TRANSPARENT)
        x = int(cx - rotated.width / 2)
        # -2: the strokes plus the downward shadow sit low in their layer
        y = int(H / 2 - rotated.height / 2 + BOB * swing) - 2
        mask = rotated.point(lambda p: 255 if p else 0, "L")
        img.paste(rotated, (x, y), mask)
    return img


def main():
    six, seven = digit_layer(SIX), digit_layer(SEVEN)
    frames = [frame(i, six, seven) for i in range(FRAMES)]
    buf = io.BytesIO()
    frames[0].save(buf, "GIF", save_all=True, append_images=frames[1:], duration=FRAME_MS,
                   loop=0, transparency=TRANSPARENT, disposal=2, optimize=False)
    data = buf.getvalue()

    rows = []
    for off in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[off:off + 16]) + ",")
    OUT.write_text(
        "#pragma once\n"
        '#include "lvgl.h"\n\n'
        "// Generated by scripts/gen_easter_egg_gif.py; edit that script, not this file.\n"
        f"// Original OPad artwork ({len(data)} bytes, {FRAMES} frames, {W}x{H}), MIT licensed.\n"
        "static const uint8_t s_easter_egg_gif_map[] = {\n"
        + "\n".join(rows) + "\n"
        "};\n\n"
        "static const lv_image_dsc_t s_easter_egg_gif_dsc = {\n"
        "    .header = {\n"
        "        .magic = LV_IMAGE_HEADER_MAGIC,\n"
        "        .cf = LV_COLOR_FORMAT_RAW,\n"
        "        .flags = 0,\n"
        "        .w = 0,\n"
        "        .h = 0,\n"
        "        .stride = 0,\n"
        "        .reserved_2 = 0,\n"
        "    },\n"
        "    .data_size = sizeof(s_easter_egg_gif_map),\n"
        "    .data = s_easter_egg_gif_map,\n"
        "};\n"
    )
    print(f"Wrote {OUT} ({len(data)} bytes GIF)")


if __name__ == "__main__":
    main()
